import { observable } from "mobx";
import Head from "next/head";
import Image from "next/image";
import { Google } from "../contexts/google-user";
import styles from "../styles/Home.module.css";

export default function Home() {
  const routes: { link: string; title: string }[] = [
    {
      link: "/login",
      title: "Log in",
    },
  ];

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        Hola
        <div>
          {routes.map((route) => (
            <a href={route.link}>{`Go to ${route.title}`}</a>
          ))}
        </div>
        <div>Logged as: </div>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{" "}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  );
}
